version: "3"

services:
    database:
        image: mysql:5.7.30
        container_name: database
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: silva
            MYSQL_DATABASE: herois
            MYSQL_USER: silva
            MYSQL_PASSWORD: silva
        ports: 
            - "3308:3306"
        networks: 
            - backNetwork
    heroisapi:
        container_name: herois-api
        image: alvaro2019/spring-boot:1.0 
        restart: always
        working_dir: /herois
        ports:
            - "9000:9000"
        command: mvn spring-boot:run
        depends_on: 
            - database
        networks: 
            - backNetwork
            - frontNetwork
    heroisclient:
        image: alvaro2019/herois-angular:1.0
        restart: always
        ports: 
            - "4200:80"
        depends_on: 
            - heroisapi
        networks:
            - frontNetwork 
networks:
    backNetwork:
        driver: bridge
    frontNetwork:
        driver: bridge
